version: "3"
services:

    uzeep:
      build: ./flaskzip/
      container_name: "uzeep"
      ports:
        - 5000:5000
      environment:
        - FLASK_APP=app.py
        - FLASK_ENV=development
        - SECRET_KEY=secret
